version: "3.1"
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: onesport_shop
        volumes:
            - "./docker/db:/var/lib/mysql"
        ports:
            - "3306:3306"
